// Generated by ReScript, PLEASE EDIT WITH CARE


function useUserData(param) {
  var request = new XMLHttpRequest();
  request.addEventListener("load", (function (param) {
          var response = JSON.parse(request.response);
          console.log(response.message);
          
        }));
  request.addEventListener("error", (function (param) {
          console.log("Error logging here");
          
        }));
  request.open("GET", "http://localhost:3001/api/v1/user/login");
  request.send();
  
}

export {
  useUserData ,
  
}
/* No side effect */
